RabbitMQProject_WordToPdf.Publisher/Models/ErrorViewModel.cs
using System;

namespace RabbitMQProject_WordToPdf.Publisher.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RabbitMQProject_WordToPdf.Publisher/Models/WordFile.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RabbitMQProject_ConvertFormatWordFile.Publisher.Models
{
    public class WordFile
    {
        public string Email { get; set; }
        public IFormFile File { get; set; }
    }
}

RabbitMQProject_WordToPdf.Publisher/Controllers/ConvertController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RabbitMQProject_ConvertFormatWordFile.Publisher.Models;
using RabbitMQProject_ConvertFormatWordFile.Publisher.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RabbitMQProject_ConvertFormatWordFile.Publisher.Controllers
{
    public class ConvertController : Controller
    {
        RabbitMQPublisher _publisher;
        private readonly ILogger<ConvertController> _logger;

        public ConvertController(RabbitMQPublisher publisher, ILogger<ConvertController> logger)
        {
            _publisher = publisher;
            _logger = logger;
        }

        public IActionResult WordToPdfPage()
        {
            return View();
        }

        public IActionResult WordToZipPage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult WordToPdfPage(WordFile wordFile)
        {
            _publisher.Publish(wordFile);
            ViewBag.result = "After converting the word file to a pdf file, it will be sent to your email address.";
            return View();
        }

        [HttpPost]
        public IActionResult WordToZipPage(WordFile wordFile)
        {
            _publisher.Publish(wordFile);
            ViewBag.result = "After converting the word file to a zip file, it will be sent to your email address.";
            return View();
        }
    }
}

RabbitMQProject_WordToPdf.Publisher/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RabbitMQProject_WordToPdf.Publisher.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RabbitMQProject_ConvertFormatWordFile.Publisher.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RabbitMQProject_WordToPdf.Publisher/Views/Convert/WordToPdfPage.cshtml
@{
    ViewData["Title"] = "WordToPdfPage";
}

@model RabbitMQProject_ConvertFormatWordFile.Publisher.Models.WordFile

<h3>Convert File Word to Pdf</h3>

<div class="row">
    <div class="col-md-4">
        <form asp-action="WordToPdfPage" asp-controller="Convert" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input type="file" asp-for="File" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Convert" />
            </div>
        </form>
    </div>
</div>
@if (ViewBag.result != null)
{
    <div class="row">
        <div class="alert alert-primary" role="alert">
            @ViewBag.result
        </div>
    </div>
}

RabbitMQProject_WordToPdf.Publisher/Views/Convert/WordToZipPage.cshtml
@{
    ViewData["Title"] = "WordToZipPage";
}

@model RabbitMQProject_ConvertFormatWordFile.Publisher.Models.WordFile

<h3>Convert File Word to Zip</h3>

<div class="row">
    <div class="col-md-4">
        <form asp-action="WordToZipPage" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="File" class="control-label"></label>
                <input type="file" asp-for="File" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Convert" />
            </div>
        </form>
    </div>
</div>
@if (ViewBag.result != null)
{
    <div class="row">
        <div class="alert alert-primary" role="alert">
            @ViewBag.result
        </div>
    </div>
}

RabbitMQProject_WordToPdf.Publisher/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RabbitMQProject_WordToPdf.Publisher/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RabbitMQProject_WordToPdf.Publisher</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Converter</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Convert" asp-action="WordToPdfPage">Word To Pdf</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Convert" asp-action="WordToZipPage">Word To Zip</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - RabbitMQProject_WordToPdf.Publisher - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>